# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://binarydud.github.io
title: itybits
subtitle: A little bit of this.
author: Matt George
simple_search: http://google.com/search
description:

source:      .
destination: ./_site
plugins:     ./_plugins

excerpt_separator: <!--more-->
pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_block
metadata:
  _posts:
    - name: "title"
      field:
        element: "text"
        label: "Title"
        value: ""
    - name: 'layout'
      field:
        element: 'hidden'
        value: 'post'